/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class meteordevelopment_pulsar_rendering_Svg */

#ifndef _Included_meteordevelopment_pulsar_rendering_Svg
#define _Included_meteordevelopment_pulsar_rendering_Svg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     meteordevelopment_pulsar_rendering_Svg
 * Method:    plutojni_load_from_memory
 * Signature: (JIJIID)J
 */
JNIEXPORT jlong JNICALL Java_meteordevelopment_pulsar_rendering_Svg_plutojni_1load_1from_1memory
  (JNIEnv *, jclass, jlong, jint, jlong, jint, jint, jdouble);

/*
 * Class:     meteordevelopment_pulsar_rendering_Svg
 * Method:    plutojni_surface_get_data
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_meteordevelopment_pulsar_rendering_Svg_plutojni_1surface_1get_1data
  (JNIEnv *, jclass, jlong);

/*
 * Class:     meteordevelopment_pulsar_rendering_Svg
 * Method:    plutojni_surface_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_meteordevelopment_pulsar_rendering_Svg_plutojni_1surface_1destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
